import type { QuizWithQuestions } from "@/lib/types";

export const seededQuiz: QuizWithQuestions = {
  id: "b16b9fc0-9e12-46ea-a1a4-9c4c1f7ab101",
  slug: "northants-challenge-week-1",
  title: "How Well Do You Know Northamptonshire?",
  description: "A fast, local knowledge quiz to see how well you really know Northamptonshire.",
  is_published: true,
  is_active: true,
  starts_at: "2026-04-14T00:00:00+00:00",
  ends_at: null,
  time_limit_seconds: 15,
  created_at: "2026-04-14T00:00:00+00:00",
  questions: [
    {
      id: "c2c2eabf-9f59-4d33-91a1-f93d3ec30101",
      quiz_id: "b16b9fc0-9e12-46ea-a1a4-9c4c1f7ab101",
      sort_order: 1,
      type: "emoji_clue",
      prompt: "Guess the Northamptonshire place from the emojis:",
      extra_text: "🏁 🏎️ 🇬🇧",
      image_url: null,
      options: ["Silverstone", "Rushden Lakes", "Stanwick Lakes", "Althorp"],
      correct_index: 0,
      explanation: "Silverstone is associated with British motor racing.",
      category: "landmarks",
      difficulty: "easy",
      created_at: "2026-04-14T00:00:00+00:00",
    },
    {
      id: "c2c2eabf-9f59-4d33-91a1-f93d3ec30102",
      quiz_id: "b16b9fc0-9e12-46ea-a1a4-9c4c1f7ab101",
      sort_order: 2,
      type: "local_knowledge",
      prompt: "Stanwick Lakes is best described as:",
      extra_text: null,
      image_url: null,
      options: [
        "A 750-acre nature reserve and countryside attraction",
        "A shopping centre",
        "A castle and gardens",
        "A motorsport venue",
      ],
      correct_index: 0,
      explanation: "Stanwick Lakes is a 750-acre nature reserve and countryside attraction.",
      category: "nature",
      difficulty: "easy",
      created_at: "2026-04-14T00:00:00+00:00",
    },
    {
      id: "c2c2eabf-9f59-4d33-91a1-f93d3ec30103",
      quiz_id: "b16b9fc0-9e12-46ea-a1a4-9c4c1f7ab101",
      sort_order: 3,
      type: "days_out_round",
      prompt: "Wicksteed Park is in which Northamptonshire town?",
      extra_text: null,
      image_url: null,
      options: ["Kettering", "Towcester", "Rushden", "Daventry"],
      correct_index: 0,
      explanation: "Wicksteed Park is in Kettering.",
      category: "family_days_out",
      difficulty: "easy",
      created_at: "2026-04-14T00:00:00+00:00",
    },
    {
      id: "c2c2eabf-9f59-4d33-91a1-f93d3ec30104",
      quiz_id: "b16b9fc0-9e12-46ea-a1a4-9c4c1f7ab101",
      sort_order: 4,
      type: "true_statement",
      prompt: "Which statement is true?",
      extra_text: null,
      image_url: null,
      options: [
        "Northampton Museum and Art Gallery is famous for one of the largest shoe collections in the world",
        "Rushden Lakes is a Norman castle",
        "Silverstone is a wetland reserve",
        "Althorp is a shopping centre",
      ],
      correct_index: 0,
      explanation: "Northampton Museum and Art Gallery is famous for its shoe collection.",
      category: "culture",
      difficulty: "medium",
      created_at: "2026-04-14T00:00:00+00:00",
    },
    {
      id: "c2c2eabf-9f59-4d33-91a1-f93d3ec30105",
      quiz_id: "b16b9fc0-9e12-46ea-a1a4-9c4c1f7ab101",
      sort_order: 5,
      type: "clue_round",
      prompt: "Which place fits these clues?",
      extra_text: "Built after 1066 • linked to William the Conqueror • historic castle",
      image_url: null,
      options: ["Rockingham Castle", "Rushden Lakes", "Stanwick Lakes", "Northampton Museum"],
      correct_index: 0,
      explanation: "Rockingham Castle dates back to the Norman period and is linked to William the Conqueror.",
      category: "heritage",
      difficulty: "medium",
      created_at: "2026-04-14T00:00:00+00:00",
    },
    {
      id: "c2c2eabf-9f59-4d33-91a1-f93d3ec30106",
      quiz_id: "b16b9fc0-9e12-46ea-a1a4-9c4c1f7ab101",
      sort_order: 6,
      type: "local_knowledge",
      prompt: "West Northamptonshire Council serves which areas?",
      extra_text: null,
      image_url: null,
      options: [
        "Daventry, Northampton and South Northamptonshire",
        "Corby, Rushden and Oundle",
        "Kettering, Wellingborough and Rushden Lakes",
        "Silverstone, Towcester and Rockingham Castle",
      ],
      correct_index: 0,
      explanation: "West Northamptonshire Council serves Daventry, Northampton and South Northamptonshire.",
      category: "local_government",
      difficulty: "medium",
      created_at: "2026-04-14T00:00:00+00:00",
    },
    {
      id: "c2c2eabf-9f59-4d33-91a1-f93d3ec30107",
      quiz_id: "b16b9fc0-9e12-46ea-a1a4-9c4c1f7ab101",
      sort_order: 7,
      type: "heritage_round",
      prompt: "Which Northamptonshire town is described as the oldest town in the county?",
      extra_text: null,
      image_url: null,
      options: ["Towcester", "Rushden", "Corby", "Brackley"],
      correct_index: 0,
      explanation: "Towcester is described as the oldest town in Northamptonshire.",
      category: "towns",
      difficulty: "medium",
      created_at: "2026-04-14T00:00:00+00:00",
    },
    {
      id: "c2c2eabf-9f59-4d33-91a1-f93d3ec30108",
      quiz_id: "b16b9fc0-9e12-46ea-a1a4-9c4c1f7ab101",
      sort_order: 8,
      type: "days_out_round",
      prompt: "Which place is known for shopping, dining and leisure, and as a gateway to the Nene Wetlands?",
      extra_text: null,
      image_url: null,
      options: ["Rushden Lakes", "Silverstone", "Northampton Museum", "Rockingham Castle"],
      correct_index: 0,
      explanation: "Rushden Lakes combines shopping, dining and leisure with access to the Nene Wetlands.",
      category: "days_out",
      difficulty: "easy",
      created_at: "2026-04-14T00:00:00+00:00",
    },
  ],
};

export const seededAdminEmail = "admin@northantschallenge.co.uk";
